### PR TITLE
Added new module utils.py and "fixed" some indents

### PR DESCRIPTION
**Pull request by yandy-r**
Added a new module utils.py which has convertSize() to convert between kB and Mb and so forth. Will allow to show output in more human readable format.. test below, but not actually in effect yet, just for demonstration.

instead of showing this, look at lines **free_system_memory** and **total_system_memory** in specific.

```
$ python main.py -i 10.17.31.51 -m arista -n 'SW1' -f getFacts
{   'connect_ip': '10.17.31.51',
    'cpu_utilization': u'Cpu(s): 10.0%us',
    'free_system_memory': 1327828,
    'hostname': u'eos-sw01',
    'platform': u'DCS-7050T-64-R',
    'serial_number': u'JPE13020644',
    'system_uptime': u' 7:53',
    'total_sytem_memory': 3990500,
    'var_name': 'dev',
    'vendor': 'arista',
    'version': u'4.13.2F'}
```

we can show this if needed

```
$ python main.py -i 10.17.31.51 -m arista -n 'SW1' -f getFacts
{   'connect_ip': '10.17.31.51',
    'cpu_utilization': 'Cpu(s): 10.0%us',
    'free_system_memory': '1296.5 MiB',
    'hostname': 'eos-sw01',
    'platform': 'DCS-7050T-64-R',
    'serial_number': 'JPE13020644',
    'system_uptime': ' 7:39',
    'total_sytem_memory': '3.8 GiB',
    'var_name': 'dev',
    'vendor': 'arista',
    'version': '4.13.2F'}
```

### CODE REVIEW

**Comment by sjiveson** [comment]
Yandy, based on the change in the value in your example it looks like binary prefixes are being used, rather than metric (SI) ones. Could you double-check against some manual cli output to confirm that's what's you'd see there please?

**Comment by yandy-r** [comment]
The change is not the binary prefix, the binary prefix is the standard (unicode) u'something' returned by the JSON value. The change didn't have the prefix, that was just me wrapping an str(value) around it. The u'vlaue' representation has always been there.

**Comment by sjiveson** [comment]
Sorry, that's not what I meant, what I did mean was the free_system_memory and total_system_memory values are formatted by convertSize() using binary prefixes, not metric ones. Is this correct? Is this how the values are shown at the CLI or are they (using the examples in your comment) 1327Mb and 3.99Gb?

**Comment by jedelman8** [comment]
Going to commit this for now although as for formatting, don't think we should use "GiB" rather "GB" or "MB."  Easier to always divide by 1024? Can always make that change at a later date.

**Comment by yandy-r** [comment]
@sjiveson That was just how the function returns the values, can be changed at any time, from GiB to GB and so forth.

Just so you guys know, it's not actually applied or in place anywhere, I put it into action to make sure it did as intended. The display/representation can always be changed. Feel free to update it, change it if you want. I added it in case it may be useful later on, those utils that may be needed/wanted, but don't really require their own class.

we can always device by 1024, but I added the option for 1000 in case we ever want to do bandwidth conversion, not just data. Like I said, play with it if you want, there's still allot of checks to do inside, it assumes allot of things right now.

**Comment by sjiveson** [comment]
@IPyandy Thanks, understood. It's a tricky one, do we mimic what the CLI (or management GUI) displays or do we 'standardise' the output from CPAL (allowing fair comparison between devices etc.) I'd rather not mimic vendor/product inconsistencies but this might confuse users.

**Comment by yandy-r** [comment]
Yup, CLI actually shows something like '3990500 kB' but the API calls only sends back the number, which is fine. Gives more flexibility and easier to convert to float/int if calculations ever needed to be made. For the getFacts() makes sense to have "raw" values, incase we need calculations of any keys. I just showed it that way as demonstration, not meant to be used in there at all.

But if the need ever arises to display something, somewhere in  more friendly way, then we can use this to standardize that, that's the intent anyway. :)

**Pull request merged**
